name: Build and Release ROS2 Jazzy
description: |
  This action builds and releases a ROS2 package using the Haru Jazzy Generic container.
  It requires the following secrets to be set in the repository.
on:
  push:
    branches:
      - jazzy_debian

jobs:
  release:
    runs-on: self-hosted
    container:
      image: ghcr.io/haru-project/haru-generic-jazzy:latest
      credentials:
        username: ${{ secrets.CR_USERNAME }}
        password: ${{ secrets.CR_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: haru-project/action-build-ros2-package
          token: ${{ secrets.CI_TOKEN }}
          path: .github/actions/action-build-ros2-package
      - name: 'Clone, build and publish ROS 2 package'
        uses: ./.github/actions/action-build-ros2-package
        id: action-build-ros2-package
        with:
          UPO_SERVER: ${{ secrets.UPO_SERVER }}
          UPO_USER: ${{ secrets.UPO_USER }}
          UPO_PASSWORD: ${{ secrets.ROBOTICS_PASSWORD }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TOKEN }}